// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TickklasdfasTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tickklasdfas() {
    driver.Navigate().GoToUrl("https://ticktick.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1066, 607);
    driver.FindElement(By.LinkText("Sign Up for Free")).Click();
    driver.FindElement(By.LinkText("Войти")).Click();
    driver.FindElement(By.Id("emailOrPhone")).SendKeys("a.dzhunushodzhaev@gmail.com");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("Isa4emnjc1");
    driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("password")).SendKeys("Isa4emnjc1");
    driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
  }
}
